## This functions will cache the inverse of a matrix
## 

## This function will generate a matrix object that can store of inverse
##of that matrix

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) i <<- inverse
  getinverse <- function() i
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}


## This function will use matrix generated by makeCacheMatrix
##and uses inverse present in that object,if the inverse is not yet
##calculated then this function will calculate the same and stores it
##in the object for later use

cacheSolve <- function(x, ...) {
  i <- x$getinverse()
  if(!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setinverse(i)
  i
}
